### ISSUE TITLE
First unlock jenkind

### ISSUE THREAD

**Issue by kazek127** [jenkinsci/docker#1624] opened 2023-05-13 13:32 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

debian

### Reproduction steps

docker run -p 8080:8080 -p 50000:50000 --restart=on-failure -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11

login in to web, and put a password, page is the same but in log I see:

	at hudson.security.AuthenticationProcessingFilter2.successfulAuthentication(AuthenticationProcessingFilter2.java:74)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:237)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Expected Results

page should redirect to next steps setup jenkins.

### Actual Results

Page is this same

**Comment by dduportal** [comment] 2023-05-13 14:14
Hi @kazek127 thanks for raising this issue.

I can't reproduce the issue (macOS with Docker Desktop latest and Ubuntu 22.04 with Docker CE 23.0.6).

Could you share more of the log (ideally, all of the log) so we could help more: the error stack you provided is incomplete so it's hard to tell what is going wrong

**Comment by kazek127** [comment] 2023-05-13 14:23
This is directly from docker log:
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2023-05-13 13:24:30.310+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @564ms to org.eclipse.jetty.util.log.JavaUtilLog
2023-05-13 13:24:30.404+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2023-05-13 13:24:31.661+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2023-05-13 13:24:31.724+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.46.v20220331; built: 2022-03-31T16:38:08.030Z; git: bc17a0369a11ecf40bb92c839b9ef0a8ac50ea18; jvm 17.0.3+7
2023-05-13 13:24:32.057+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2023-05-13 13:24:32.109+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2023-05-13 13:24:32.110+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2023-05-13 13:24:32.111+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2023-05-13 13:24:32.617+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2023-05-13 13:24:32.759+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@2416498e{Jenkins v2.356,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2023-05-13 13:24:32.779+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4b45dcb8{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2023-05-13 13:24:32.779+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @3034ms
2023-05-13 13:24:32.780+0000 [id=26]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2023-05-13 13:24:33.056+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2023-05-13 13:24:33.081+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2023-05-13 13:24:33.943+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2023-05-13 13:24:33.948+0000 [id=35]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2023-05-13 13:24:33.961+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2023-05-13 13:24:34.527+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2023-05-13 13:24:34.528+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2023-05-13 13:24:34.529+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2023-05-13 13:24:34.530+0000 [id=33]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2023-05-13 13:24:34.581+0000 [id=51]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Download metadata
2023-05-13 13:24:34.588+0000 [id=51]	INFO	hudson.util.Retrier#start: Attempt #1 to do the action check updates server
2023-05-13 13:24:35.140+0000 [id=38]	INFO	jenkins.install.SetupWizard#init: 

*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. An admin user has been created and a password generated.
Please use the following password to proceed to installation:

ca767889105c456f9ede5b7701c0d4a3

This may also be found at: /var/jenkins_home/secrets/initialAdminPassword

*************************************************************
*************************************************************
*************************************************************

2023-05-13 13:24:47.079+0000 [id=36]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2023-05-13 13:24:47.102+0000 [id=25]	INFO	hudson.lifecycle.Lifecycle#onReady: Jenkins is fully up and running
2023-05-13 13:24:47.636+0000 [id=51]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
2023-05-13 13:24:47.637+0000 [id=51]	INFO	hudson.util.Retrier#start: Performed the action check updates server successfully at the attempt #1
2023-05-13 13:24:47.640+0000 [id=51]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Download metadata. 13,059 ms
2023-05-13 13:25:17.538+0000 [id=75]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException
java.lang.IllegalStateException: Response is committed
	at org.eclipse.jetty.server.Request.getSession(Request.java:1623)
	at org.eclipse.jetty.server.Request.getSession(Request.java:1602)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:279)
	at hudson.security.AuthenticationProcessingFilter2.successfulAuthentication(AuthenticationProcessingFilter2.java:74)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:237)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-13 14:01:40.605+0000 [id=80]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Started Periodic background build discarder
2023-05-13 14:01:40.607+0000 [id=80]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$1: Finished Periodic background build discarder. 1 ms


dawid@debian:~/jenkins$ docker --version
Docker version 23.0.2, build 569dd73

dawid@debian:~/jenkins$ cat /etc/debian_version
11.6

**Comment by dduportal** [comment] 2023-05-13 14:31
Does it work if you do the same with your web-browser in anonymous mode?

**Comment by kazek127** [comment] 2023-05-13 14:43
Look's like that help and wizard move forward. I setup jenkin and reboot. Now I have normal login window. I put new admin user and password and it is stop on this same page. If I run again incognito mode then is working fine. Some security settings in jenkins is breaking it or something with chrome?

**Comment by dduportal** [comment] 2023-05-13 15:01
Usually, the error ` java.lang.IllegalStateException: Response is committed` is related to a value in the Cookies sent by your webbrowser that is confusing for the remote web server (in this case Jenkins).

The fact it's working with the incognito mode confirms this is related to the web-session.

Most probably, you've used a lot of different Jenkins instances with the same `localhost` URL so the cookies should be cleaned up for this domain to definitively solve the issue.

**Comment by kazek127** [comment] 2023-05-13 15:06
This was my first run Jenkins. I also cleared Chrome to default and the results are the exact nothing changed :/

**Comment by dduportal** [comment] 2023-05-13 15:41
Interesting. Do you have the same behavior with another web browser ?

**Comment by kazek127** [comment] 2023-05-13 15:48
It only happens on Chrome. On Firefox or IE working correctly. At first, I think maybe some plugin in chrome stopped working correctly, but I remove it and run again and it provides the same results.

**Comment by dduportal** [comment] 2023-05-15 16:33
Thanks for the answers.

Btw I still got a few question to decide if it is an issue with the docker image or with Jenkins itslef (which would be another issue tracker).

- What is the Jenkins version in your image? (you did not fill the issue with this information)
- Do you have the same behavior with the JDK17 (image `jenkins/jenkins:lts-jdk11`)?
- Do you have the same issue if you start the same **exact** Jenkins version without Docker on your machine (get a JDK and run the generic WAR file from https://www.jenkins.io/download/)?

**Comment by dduportal** [comment] 2023-05-17 15:14
> Right now I'm using jenkins/jenkins:jdk17-preview image

This image should not be used anymore: use `jenkins/jenkins:lts-jdk17` instead.

Also, can you share the Jenkins version you have + the plugin list and versions please?

**Comment by dduportal** [comment] 2023-05-17 15:31
Can you check if you have the same behavior for the following:

- `jenkins/jenkins:jdk11` (should be 2.405 version of Jenkins)
- `jenkins/jenkins:lts-jdk17` (should be 2.387.3 version of Jenkins)

?

**Comment by kazek127** [comment] 2023-05-19 08:52
jenkins/jenkins:jdk11 (should be 2.405 version of Jenkins)
jenkins/jenkins:lts-jdk17 (should be 2.387.3 version of Jenkins)


That is correct and I need to use FF browser. In chrome this same case I need to use in "incognito mode"

**Comment by dduportal** [comment] 2023-05-19 09:02
> jenkins/jenkins:jdk11 (should be 2.405 version of Jenkins) jenkins/jenkins:lts-jdk17 (should be 2.387.3 version of Jenkins)
> 
> That is correct and I need to use FF browser. In chrome this same case I need to use in "incognito mode"

This is definitively related to your Chrome session: could you try with either a fresh Chrome installation, or after cleaning all elements (cookies, caches, etc.) for the domain you're using to reach Jenkins?

**Comment by MarkEWaite** [comment] 2023-11-14 01:23
Closing after months with no further response.

**Closed by MarkEWaite** 2023-11-14 01:23 UTC
Labels: question
