### ISSUE TITLE
Missing "Uninstall" plugin section #1531

### ISSUE THREAD

**Issue by movies0** [jenkinsci/docker#1971] opened 2024-12-18 07:34 UTC
Removing Plugins from a Jenkins Installation
The [Jenkins Docker documentation](https://github.com/jenkinsci/docker#preinstalling-plugins) provides detailed instructions for adding plugins to a Jenkins controller image. However, it lacks guidance on removing plugins from an existing Jenkins installation, which can be non-intuitive for users unfamiliar with how the image and entrypoint script work. This guide aims to fill that gap with clear, actionable steps.

Steps to Remove a Plugin
1. Update the plugins.txt or Equivalent jenkins-plugin-cli Call
If you’re using a custom Docker image with a plugins.txt file or jenkins-plugin-cli, start by ensuring the plugin is removed from this configuration. For example:

If your plugins.txt includes the plugin windows-slaves, remove the corresponding line:

diff
Copy code
- windows-slaves
Alternatively, if using jenkins-plugin-cli commands, ensure the plugin is excluded from any install-plugin commands in your Dockerfile.

2. Verify Plugins in the Base Image
Build your custom Docker image and ensure the plugin is no longer present in /usr/share/jenkins/ref/plugins/. Use the following command to diagnose:

bash
Copy code
docker run --rm your-custom-jenkins-image ls -l /usr/share/jenkins/ref/plugins/
If the plugin windows-slaves.jpi is absent, you’ve successfully removed it from the base image.

3. Check and Remove the Plugin from $JENKINS_HOME
Even after removal from the base image, the plugin may persist in the Jenkins data volume ($JENKINS_HOME/plugins/) because the entrypoint script does not automatically delete plugins. To completely remove the plugin:

Option 1: Remove via the Jenkins UI
Navigate to Manage Jenkins > Manage Plugins, locate the plugin in the Installed tab, and uninstall it. Then, restart Jenkins to apply the changes.

Option 2: Remove Manually from the File System
If you prefer a manual approach, delete the plugin files directly from $JENKINS_HOME/plugins/:

bash
Copy code
docker exec -it jenkins-container bash
rm -rf $JENKINS_HOME/plugins/windows-slaves*
Afterward, restart the Jenkins container:

bash
Copy code
docker restart jenkins-container
4. Validate Plugin Removal
Confirm the plugin has been completely removed by checking both directories:

Ensure it’s not present in the base image’s plugin directory:

bash
Copy code
docker exec -it jenkins-container ls -l /usr/share/jenkins/ref/plugins/
Verify it’s absent from $JENKINS_HOME/plugins/:

bash
Copy code
docker exec -it jenkins-container ls -l $JENKINS_HOME/plugins/
Additionally, inspect the Jenkins UI to confirm the plugin no longer appears under Manage Plugins.

Example: Removing the windows-slaves Plugin
Using the above steps, here’s a practical example for removing the windows-slaves plugin:

Update your plugins.txt file or jenkins-plugin-cli command to exclude windows-slaves.
Rebuild your custom Jenkins Docker image and verify the plugin is not in /usr/share/jenkins/ref/plugins/.
Remove the plugin files from $JENKINS_HOME/plugins/ via the Jenkins UI or manually delete them from the filesystem.
Restart the Jenkins container and confirm the removal.
Key Considerations
Data Persistence: Jenkins stores plugin configurations and data in $JENKINS_HOME. Removing a plugin from the base image does not automatically clean up data from the persistent volume.
Restart Required: Always restart the Jenkins container after removing plugins to ensure changes take effect.
By following these steps, you can confidently remove plugins from your Jenkins installation, maintaining a clean and optimized environment.

**Comment by dduportal** [comment] 2024-12-18 08:17
Duplicate of #1531

Also, please do not use an LLM to generate content wasting maintainers time. We expect a proper discussion and due diligence in searching existing issues. Additionally, the problem has to be treated on the www.jenkins.io and adding an eventual link in this repository.

**Closed by dduportal** 2024-12-18 08:17 UTC
