### ISSUE TITLE
Can't not use the docker environment for jenkins agent.

### ISSUE THREAD

**Issue by Zhaoningx** [jenkinsci/docker#1258] opened 2021-12-20 08:03 UTC
Hi all,
I'm using Jenkins,  I met an issue when I want to add a Jenkins node.

My Jenkins server is set up in a NUC(as a server), and the node I want to set up is in another NUC(as an agent), I generated the ssh key and added Credential to connect between the server and the new node, it works. But the testing environment is set up in the docker of the agent NUC, so I used the scripts as below:

```
stage ("Running for testing") {
    steps {
        // run scripts
        sh """
        sudo docker exec -it nuc_a /bin/bash
        """
    }
}
```

But it showed me an error "no TTY device", I'm not familiar with the Jenkins/docker, so do you know how to jump into the environment of the docker in the agent NUC? If not, do you know how to set up a node by using the docker environment directly? Thanks very much.

**Comment by tobiasherzke** [comment] 2022-01-19 15:58
"no TTY device" comes from sudo trying to read a password. You can execute pipeline stages in docker containers by configuring a Docker Cloud and Docker Agent templates in http://your-jenkins/configureClouds. Give your Docker Agent template a label. Then in your pipeline stage, include a line `agent {label "yourLabelHere"}`.

This is not a bug. You should close it. See the community forum for questions like this. https://community.jenkins.io/

**Closed** 2022-01-19 16:58 UTC
Labels: bug

**Comment by Zhaoningx** [comment] 2022-01-20 01:25
Hi @tobiasherzke, thanks so much, fixed it by creating a docker agent instead.
