### ISSUE TITLE
Default plugins broken (credentials-binding, jackson2-api, github)

### ISSUE THREAD

**Issue by krangerich** [jenkinsci/docker#952] opened 2020-05-10 08:25 UTC
After installing jenkins/jenkins:lts (=2.222.3), a lot of the default plugins cannot be installed because of failed dependencies:

2020-05-10 08:11:29.371+0000 [id=91]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install credentials-binding
java.io.IOException: Downloaded file /var/jenkins_home/plugins/credentials-binding.jpi.tmp does not match expected SHA-256, expected '0tsPEoS2UEI3UUApcvSLUqkiisETySJxCNGeY9bXejo=', actual '7pCDZev0yZfcXd15LNWC1KDmGsPhF8rYuUIBKp+7sHY='

java.io.IOException: Downloaded file /var/jenkins_home/plugins/jackson2-api.jpi.tmp does not match expected SHA-256, expected 'MpjSdkuA3ZvAhDz5RLdyB+zN2qNRxdHgPa52kKqC45M=', actual 'G44spiRRttv5h0aH+6LZvub1+UlzREnIbg7OAUglwqM='

java.io.IOException: Downloaded file /var/jenkins_home/plugins/github.jpi.tmp does not match expected SHA-256, expected 'BZj7VvRWjVOSovmAQBaPdhs7B3XY0XK73o5VZoNK7Eo=', actual 'XYoPrsxXINvXn7hdzrr+8oGnAx69LC1gShXb4QKpFmM='

I've no idea how to fix this, so basically jenkins/jenkins:lts is currently broken.

**Comment by robert14-els** [comment] 2020-05-10 09:05
This morning (BST) I have been seeing lots of 404s when using `install-plugins.sh` script to install plugins.
It now looks like the `latest` directory has been added to `2.222` folder https://updates.jenkins.io/2.222/

`latest/ | 2020-05-10 09:01 | - |  `

However now with the `latest` and `lts` tags I get lots of corruption issues
```
error [/usr/share/jenkins/ref/plugins/artifactory.jpi]:  missing 1176935066 bytes in zipfile
  (attempting to process anyway)
error [/usr/share/jenkins/ref/plugins/artifactory.jpi]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by daniel-beck** [comment] 2020-05-10 09:58
Sorry about the corrupt files, was an issue in the update site generator. Should be fixed now.

**Comment by robert14-els** [comment] 2020-05-10 10:02
I have just run another build and am getting the same
e.g.
```
Downloading plugin: ec2 from https://updates.jenkins.io/download/plugins/ec2/latest/ec2.hpi
Downloaded file is not a valid ZIP: /usr/share/jenkins/ref/plugins/ec2.jpi
error [/usr/share/jenkins/ref/plugins/ec2.jpi]:  missing 4018201010 bytes in zipfile
  (attempting to process anyway)
error [/usr/share/jenkins/ref/plugins/ec2.jpi]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
Download integrity: ec2
```

```
Some plugins failed to download! Download integrity: blueocean
Download integrity: ec2
Download integrity: junit
Download integrity: artifactory
Download integrity: credentials-binding
Download integrity: echarts-api
```
I will give it an hour and see if it is a replication thing.
Thanks for the update though!

**Comment by daniel-beck** [comment] 2020-05-10 10:04
Sadly the log of this script doesn't tell you where it's redirected to for the download 😞

**Comment by robert14-els** [comment] 2020-05-10 10:05
Sadly not. It's like a lottery of which plugins fail each time I run the script :D

**Comment by lifeofguenter** [comment] 2020-05-10 21:05
Just for visibility, having still issues with the following plugins:

```

Some plugins failed to download! Download integrity: cloudbees-bitbucket-branch-source
--
790 | Download integrity: ec2
791 | Download integrity: blueocean-config
792 | Download integrity: matrix-auth
793 | Download integrity: blueocean-events
794 | Download integrity: blueocean-jwt
795 | Download integrity: blueocean-jira
796 | Download integrity: blueocean-pipeline-api-impl
797 | Download integrity: blueocean-pipeline-editor
798 | Download integrity: blueocean-rest
799 | Download integrity: blueocean-web
800 | Download integrity: jenkins-design-language
801 | Download integrity: blueocean-pipeline-scm-api


```

**Comment by daniel-beck** [comment] 2020-05-10 21:13
Out of our mirrors, there's still one, serverion, that hasn't updated since Saturday evening UTC 😦 22 hrs old and counting…

**Comment by slide** [comment] 2020-06-23 14:10
Has this issue been resolved with the mirrors updating?

**Comment by daniel-beck** [comment] 2020-06-23 14:28
Yes, was fixed on the Monday.

**Closed by daniel-beck** 2020-06-23 14:28 UTC

**Comment by jamesrwhite** [comment] 2020-06-29 15:48
Seems this issue may have resurfaced with the latest update today.

```
15:46:44 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/2.235/latest/credentials-plugin.hpi -o /usr/share/jenkins/ref/plugins/credentials-plugin.jpi)
Failed to download plugin: credentials or credentials-plugin
15:46:44 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/2.235/latest/jackson2-api-plugin.hpi -o /usr/share/jenkins/ref/plugins/jackson2-api-plugin.jpi)
```

**Comment by slide** [comment] 2020-06-29 15:58
https://issues.jenkins-ci.org/browse/INFRA-2666

**Comment by daniel-beck** [comment] 2020-06-29 16:08
Looks like a duplicate of https://issues.jenkins-ci.org/browse/INFRA-160, again. This is a persistent issue due to how we distribute things.
