### ISSUE TITLE
When using a host volume for jenkin's home dir, that volume must be either first created by uid=1000 or you must specify user=root

### ISSUE THREAD

**Issue by bayeslearner** [jenkinsci/docker#1017] opened 2020-11-04 07:18 UTC
Those are not always the best options.   Check the closed issue #177 and #155. 

The issue is this:  
ENV COPY_REFERENCE_FILE_LOG $JENKINS_HOME/copy_reference_file.log
USER ${user}

"USER ${user}"  comes too late and the copied log file is owned by root.  When the docker container is run as uid=1000,  it will have trouble accessing those files.

**Comment by bayeslearner** [comment] 2020-11-22 22:34
nobody want to fix this for good?

**Comment by akshat-crypto** [comment] 2020-12-26 05:27
@bayeslearner hlo, i would like to try to solve this issue, if its still open. Can you pls share an example of this  issue

**Comment by timja** [comment] 2021-07-18 17:06
Duplicate of https://github.com/jenkinsci/docker/issues/933

you can rebuild the image with your own user id or create an anonymous data volume I believe @dduportal knows more about this

**Closed by timja** 2021-07-18 17:06 UTC

**Comment by dduportal** [comment] 2021-07-19 14:57
@timja that is correct: you can rebuild the image and set the `ARG` (with the `docker build` flag `--build-arg UID=XXXX` or in a changed `Dockerfile`) to achieve this goal.
