### ISSUE TITLE
Error - SEVERE: I/O when connecting with CLI toolchain. 

### ISSUE THREAD

**Issue by alexellis** [jenkinsci/docker#164] opened 2015-10-30 08:38 UTC
In the official 'java' docker I connect to my instance of the official Jenkins docker container and try to use the cli... this always gives a 'SEVERE I/O' error on every call - but it looks like the call is actually working and we're getting a correct response.

The two host port mappings are working correctly as far as I can see.

Containers run with:

```
docker run -ti java /bin/bash
docker run -p 8080:8080 -p 50000:50000 jenkins
```

Logs 'java' container 

```
root@7f15e45c592d:/# java -jar jenkins-cli.jar -s http://x.x.x.x:8080/ version
1.625.1
Oct 30, 2015 8:34:12 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel CLI connection to http://x.x.x.x:8080/
java.io.IOException: Unexpected termination of the channel
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

root@7f15e45c592d:/# 

java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b01)
OpenJDK 64-Bit Server VM (build 25.66-b01, mixed mode)
root@7f15e45c592d:/# 
```

Logs from Jenkins CI

```
Oct 30, 2015 8:34:11 AM hudson.TcpSlaveAgentListener$ConnectionHandler run
INFO: Accepted connection #7 from /172.17.42.1:54834
```

**Comment by Jnnybrrn** [comment] 2015-12-14 11:17
Experiencing the exact same issue, likewise CLI commands seem to work fine but always receive an I/O error.

Using jenkins:1.609.3

**Comment by psagrera** [comment] 2015-12-30 08:09
Same here,

Running jenkins 1.638 
root@91804978f451:/opt/robot# java -jar jenkins-cli.jar -s http://x.x.x.x:8084/ version
1.638
Dec 30, 2015 8:05:14 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel CLI connection to http://172.30.137.41:8084/
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2332)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2801)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

**Comment by carlossg** [comment] 2016-01-13 08:52
This seems to be a problem with the docker port redirection. When ran from the jenkins container no error is printed when pointed to localhost, but the error is there when going through docker exposed port.

```
jenkins@351b4b50db15:~$ java -jar jenkins-cli.jar -s http://localhost:8080 version
1.625.3
jenkins@351b4b50db15:~$ java -jar jenkins-cli.jar -s http://192.168.99.100:8080 version
1.625.3
Jan 13, 2016 8:49:15 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel CLI connection to http://192.168.99.100:8080
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

```

Also when jenkins runs in host mode there is no error

**Comment by vpal** [comment] 2016-06-01 14:52
I also have this error. If I run from the same container or connect directly to the container's IP the error is not present.
If I connect through the forwarded ports the issue is present.
The port forwards created by docker should not cause any issues.
What information would you need to investigate the cause of the issue?

 I tried to do some strace-ing and what I see is when connected directly the cli closes the connection to port 50000 for writing with "shutdown(19, SHUT_WR)       = 0" and after that it is still able to read data.

```
[pid    68] socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 19
[pid    68] setsockopt(19, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
[pid    68] setsockopt(19, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid    68] connect(19, {sa_family=AF_INET, sin_port=htons(50000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid    68] getsockopt(19, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
[pid    68] getsockname(19, {sa_family=AF_INET, sin_port=htons(48732), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
[pid    68] sendto(19, ""..., 23, 0, NULL, 0) = 23
[pid    68] recvfrom(19, ""..., 1, 0, NULL, NULL) = 1
...
[pid    85] sendto(19, ""..., 156, 0, NULL, 0) = 156
[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 469
[pid    69] sendto(19, ""..., 1148, 0, NULL, 0) = 1148
[pid    69] sendto(19, ""..., 2, 0, NULL, 0) = 2
***[pid    69] shutdown(19, SHUT_WR)       = 0
***[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
***[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
***[pid    80] recvfrom(19, ""..., 512, 0, NULL, NULL) = 218
[pid    80] shutdown(19, SHUT_RD)       = 0
```
Although when ran through the forwarded ports the client closes the connection for writing the same way and tries to read from the connection the same way but there is no data available any more.

```
[pid    68] socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 19
[pid    68] setsockopt(19, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
[pid    68] setsockopt(19, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid    68] connect(19, {sa_family=AF_INET, sin_port=htons(50000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid    68] getsockopt(19, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
[pid    68] getsockname(19, {sa_family=AF_INET, sin_port=htons(48732), sin_addr=inet_addr("127.0.0.1")}, [16]) = 0
[pid    68] sendto(19, ""..., 23, 0, NULL, 0) = 23
[pid    68] recvfrom(19, ""..., 1, 0, NULL, NULL) = 1
...
[pid    82] sendto(19, ""..., 156, 0, NULL, 0) = 156
[pid    79] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    79] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    79] recvfrom(19, ""..., 512, 0, NULL, NULL) = 512
[pid    79] recvfrom(19, ""..., 512, 0, NULL, NULL) = 469
[pid    68] sendto(19, ""..., 1148, 0, NULL, 0) = 1148
[pid    68] sendto(19, ""..., 2, 0, NULL, 0) = 2
***[pid    68] shutdown(19, SHUT_WR)       = 0
***[pid    79] recvfrom(19, "", 512, 0, NULL, NULL) = 0
Jun 01, 2016 2:39:16 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
SEVERE: I/O error in channel CLI connection to http://127.0.0.1:8080
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

[pid    79] shutdown(19, SHUT_RD)       = -1 ENOTCONN (Transport endpoint is not connected)
```

**Comment by vpal** [comment] 2016-06-02 13:10
The related server side error message looks like this:
```
Connection #229 failed
java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at hudson.TcpSlaveAgentListener$ConnectionHandler.run(TcpSlaveAgentListener.java:175)
```

**Comment by vpal** [comment] 2016-06-02 14:14
Okay so I did some additional testing and it seems that this issue is caused by iptables not handling the connection properly and closing the server side because of some reason.
It seems that this is being related to the MTU of the docker0 interface and the MTU of the interface which the cli connects through not being the same.

In my case:
```
docker0   Link encap:Ethernet  HWaddr 02:42:B6:76:67:DE  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:b6ff:fe76:67de/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:3152 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3220 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1084191 (1.0 MiB)  TX bytes:504882 (493.0 KiB)

eth0      Link encap:Ethernet  HWaddr 02:5F:92:3E:FD:75  
          inet addr:172.32.10.10  Bcast:172.32.0.255  Mask:255.255.255.0
          inet6 addr: fe80::5f:92ff:fe3e:fd75/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:58604 errors:0 dropped:0 overruns:0 frame:0
          TX packets:19590 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:155735881 (148.5 MiB)  TX bytes:3808094 (3.6 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1035 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1035 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:298640 (291.6 KiB)  TX bytes:298640 (291.6 KiB)

vetha7267ee Link encap:Ethernet  HWaddr 3E:A3:E8:67:8A:BC  
          inet6 addr: fe80::3ca3:e8ff:fe67:8abc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:289 errors:0 dropped:0 overruns:0 frame:0
          TX packets:300 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:134255 (131.1 KiB)  TX bytes:51951 (50.7 KiB)

veth05be358 Link encap:Ethernet  HWaddr 92:94:75:F4:D4:E2  
          inet6 addr: fe80::9094:75ff:fef4:d4e2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:2863 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2947 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:994064 (970.7 KiB)  TX bytes:455125 (444.4 KiB)
```

If I connect through localhost which has a different MTU than docker0 (localhost has 65536 docker0 has 9001) I get the error.
If I connect through eth0 which has the same MTU I don't get the error.

So it seems that this is broken because of iptables and iptables does this beacuse of the different MTU.

**Comment by savishy** [comment] 2016-08-08 10:48
@vpal thanks a ton for that comment, it really helped me find a workaround!

I was breaking my head over this and took a look at the MTUs after reading the above comment.
I was initializing the build using `localhost:8080` so far, i.e.

```
java -jar jenkins-cli.jar -s http://localhost:8080 build petclinic-build -s -v
```
And this was encountering the exception `java.io.IOException: Unexpected termination of the channel`.

Instead, I tried using the IP Address of the Docker Container, and this worked! 
```
java -jar jenkins-cli.jar -s http://172.17.0.2:8080 build petclinic-build -s -v
```

**Comment by vpal** [comment] 2016-08-08 20:46
@savishy You are welcome. I'm glad I was able to help.

**Closed** 2021-07-22 07:27 UTC
Labels: bug
