### ISSUE TITLE
Trying to setup Jenkins in AKS cluster.

### ISSUE THREAD

**Issue by seetharam757** [jenkinsci/docker#720] opened 2018-08-29 13:28 UTC
**_Couldn't find appropriate repo to create this issue.  So, creating here._**

### What I did
Created an AKS cluster with 2 nodes. Created a Manifest File to bring up 4 containers with the latest Jenkins image from the public registry directly. Mounted a File Share as given in https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv. Everything is working fine, the Containers are up with Jenkins service and are able to write to the mount. But, getting the error

> Error
Jenkins detected that you appear to be running more than one instance of Jenkins that share the same home directory '/var/jenkins_home’. This greatly confuses Jenkins and you will likely experience strange behaviors, so please correct the situation.

### What I expect
Need Jenkins HA in AKS with Shared Mount.

**Comment by seetharam757** [comment] 2018-08-29 13:31
Created an issue in Azure section as well - https://github.com/Azure/AKS/issues/627

**Comment by carlossg** [comment] 2018-08-29 13:36
dupe of #399

**Comment by gotviserion** [comment] 2018-09-06 19:52
Facing similar issue.  Would appreciate if someone can provide a solution for this.

**Comment by batmat** [comment] 2018-09-10 08:43
Closing in favor of #399. 

Also, please read the issue template: this repo is about issues specific to this Docker image. Two Jenkins instances cannot yet be run on the same `JENKINS_HOME`.

**Comment by batmat** [comment] 2018-09-10 08:43
See also https://jenkins.io/blog/2018/08/31/shifting-gears/ for the future improvements in this area.

**Closed by batmat** 2018-09-10 08:43 UTC
