### ISSUE TITLE
Fail to start docker in jenkins

### ISSUE THREAD

**Issue by stark-eth** [jenkinsci/docker#1568] opened 2023-02-10 07:29 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Manjaro Linux

### Reproduction steps

failed to start daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed

### Expected Results

start docker successfully

### Actual Results

failed to start daemon: error initializing graphdriver: devicemapper: Error running deviceCreate (CreatePool) dm_task_run failed

**Comment by dduportal** [comment] 2023-02-21 09:03
Hi @stark-eth , thanks for raising an issue.

First of all, you need to provide more informations to get help: what is your exact configuration, what command did you try, what are the settings?

It does not look like your problem is related to the Jenkins Docker image here: the error message is related to the container engine itself. You might want to check https://github.com/moby/moby/issues/6325.

I'm going to close this issue and to recommend you to open a topic either on the [Jenkins Community Forum](https://community.jenkins.io) or the [Docker Community Forum](https://forums.docker.com/c/community/59) to get a broader help than "only" the maintainers here.

The reason to close is that there are no elements allowing us (maintainers) to state it is a problem that we could fix on the official Jenkins Docker image.

Of course, if you are able to provide reproduction case (and that we evaluate it is a valid issue with the image), we'll reopen the issue to work on a fix!

**Closed by dduportal** 2023-02-21 09:03 UTC
Labels: bug
