### ISSUE TITLE
versionLT in jenkins-support doesn't treat newer version of workflow-cps as newer

### ISSUE THREAD

**Issue by PiersRBME** [jenkinsci/docker#1880] opened 2024-05-23 12:47 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.459
OS: Linux - 5.10.215-203.850.amzn2.x86_64
Java: 17.0.11 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
asm-api:9.7-33.v4d23ef79fcc8
aws-java-sdk-minimal:1.12.696-451.v0651a_da_9ca_ec
aws-java-sdk-secretsmanager:1.12.696-451.v0651a_da_9ca_ec
aws-secrets-manager-secret-source:1.72.v61781b_35c542
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1169.va_f810c56e895
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
cloudbees-folder:6.940.v7fa_03b_f14759
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-109.vfe16c66636eb_
configuration-as-code:1810.v9b_c30a_249a_4c
configurationslicing:548.ve92d48e66b_f8
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:677.vdc9d38cb_254d
custom-folder-icon:2.12
data-tables-api:2.0.7-1
display-url-api:2.204.vf6fddd8a_8b_e9
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
font-awesome-api:6.5.2-1
git:5.2.2
git-client:4.7.0
gson-api:2.10.1-15.v0d99f670e0a_7
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
job-dsl:1.87
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-2
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1265.v65b_14fa_f12f0
lockable-resources:1255.vf48745da_35d0
mailer:472.vf7c289a_4b_420
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.12.1-101.v85b_e08b_780dd
mina-sshd-api-core:2.12.1-101.v85b_e08b_780dd
next-build-number:1.8
oic-auth:4.269.va_7526f34f306
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:710.v4b_94b_077a_808
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2198.v41dd8ef6dd56
pipeline-model-definition:2.2198.v41dd8ef6dd56
pipeline-model-extensions:2.2198.v41dd8ef6dd56
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2198.v41dd8ef6dd56
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:182.v468b_97b_9dcb_8
plugin-util-api:4.1.0
prism-api:1.29.0-15
rbme-fargate-cloud:20240221-1204-rc-7f8a136
scm-api:690.vfc8b_54395023
script-security:1336.vf33a_a_9863911
simple-theme-plugin:176.v39740c03a_a_f5
slack:715.v1cfed1b_9c63c
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:337.v395d2403ccd4
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1311.v4250456a_e552
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3894.vd0f0248b_a_fc4
workflow-durable-task-step:1353.v1891a_b_01da_18
workflow-job:1415.v4f9c9131248b_
workflow-multibranch:791.v28fb_f74dfca_e
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:907.v6713a_ed8a_573

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker image 

### Reproduction steps

During boot the plugins are updated via copy_reference_file().
That calls on function [versionLT](https://github.com/jenkinsci/docker/blob/a1a7316d3d9838db9242fb152661005b1a614ac5/jenkins-support#L6).

The script reports:

> SKIPPED plugins/workflow-cps.jpi : Image version (3894.3896.vca_2c931e7935) is older than installed version (3894.vd0f0248b_a_fc4)

But actually version `3894.3896.vca_2c931e7935` is newer, apparently, than `3894.vd0f0248b_a_fc4`.
(I'm not sure why the version ID has this structure. One for workflow-cps team I guess.)
https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3894.3896.vca_2c931e7935

### Expected Results

For the plugin to be updated.

### Actual Results

Plugin update SKIPPED.

### Anything else?

The main Jenkins UI shows the newer version as available for upgrade.

**Comment by timja** [comment] 2024-05-23 18:35
Duplicate of https://github.com/jenkinsci/docker/issues/1456

**Comment by timja** [comment] 2024-05-23 18:36
FWIW I have tried fixing it, I wasn't able to make it work in bash for all cases. Likely possible just was taking longer than I had.

**Closed by timja** 2024-05-23 18:35 UTC
Labels: bug
