### ISSUE TITLE
No lts tag for 2.303.1 version on docker hub

### ISSUE THREAD

**Issue by ranebull** [jenkinsci/docker#1206] opened 2021-09-08 15:24 UTC
Hello! 

I see, that use lts tag on Dockerhub for
```
jenkins/jenkins:2.289.2-lts
jenkins/jenkins:2.289.3-lts
```
versions and it very useful.

Please, create **lts** tag for **2.303.1** version.

Thank you!

**Comment by timja** [comment] 2021-09-08 15:51
Duplicate of https://github.com/jenkinsci/docker/issues/1196

**Closed by timja** 2021-09-08 15:51 UTC
Labels: bug
