### ISSUE TITLE
inalize namespace drop capabilities open /proc/1/status: permission denied 

### ISSUE THREAD

**Issue by suchisubhra** [jenkinsci/docker#78] opened 2015-04-15 21:43 UTC
I am able to  run  all  my  docker  images...but whenever  i  am running jenkins container it is failing
docker run -p 8080:8080 jenkins 

Error response from daemon: Cannot start container 32a832f36acad831ba0ec6be3af890281e90466063dc9c626820296fad36c5af: finalize namespace drop capabilities open /proc/1/status: permission denied 

I tried all  the other option you  guys mentioned but no  luck...
always getting the same issue.
Our SELINUX is disabled  and running on  centos6.6

Any  help  is really appreciated 

~Suchi

**Comment by lcc2207** [comment] 2015-05-15 15:44
I am seeing the same issue on CentOS 6.6.

**Comment by carlossg** [comment] 2015-05-15 17:26
That's a Docker/Linux issue, I don't think there is anything in this image related to that

https://bugzilla.redhat.com/show_bug.cgi?id=1096123

**Comment by pdericson** [comment] 2015-05-21 05:24
I'm seeing this on RHEL 6.6.  When I google "finalize namespace drop capabilities open /proc/1/status: permission denied" this ticket is the only exact match I find.  No idea what the issue is.

**Comment by davidcollom** [comment] 2015-06-22 09:49
One thing I've noticed is if you are loading docker images via ``docker load`` that setting the umask of the docker daemon to 022 resolved this for me.

The issue I noticed was that / was being mounted as 0750 instead of 0755. setting the umask resolved the issue (after I removed the affected image (and its children)

**Comment by carlossg** [comment] 2015-07-15 17:12
closing as this is a docker issue, not the image

**Closed by carlossg** 2015-07-15 17:12 UTC
