### ISSUE TITLE
Latest alpine based images using 3.9 alpine repo instead of 3.18

### ISSUE THREAD

**Issue by jonkipu** [jenkinsci/docker#1691] opened 2023-08-20 12:07 UTC
### Jenkins and plugins versions report

  Paste the output here

### What Operating System are you using (both controller, and any agents involved in the problem)?

Official jenkins:2.419-alpine

### Reproduction steps

1. Pull image anywhere from "jenkins:2.409-alpine" to "jenkins:2.419-alpine" (According to tags this is using alpine tag 3.18.3 as base)
2. cat /etc/apk/repositories

### Expected Results

Expect to see 3.18 repo being used

### Actual Results

3.9 alpine repo is being used

### Anything else?

I might be misunderstanding something here but it seems that if the image is using alpine 3.18.3 as its base it should use the 3.18 repo, this is validated by pulling the 3.18.3 alpine image directly and checking on that or by building the Jenkins alpine dockerfile locally

**Comment by timja** [comment] 2023-08-20 15:11
Duplicate of https://github.com/jenkinsci/docker/issues/1690

**Comment by jonkipu** [comment] 2023-08-21 07:24
@timja are you sure? This is using an older pinned tag not the lts

**Comment by dduportal** [comment] 2023-08-21 09:51
On it

**Comment by dduportal** [comment] 2023-08-21 12:02
I confirm it is the same problem as #1690. The following pinned tags have been republished by this problem:

```
grep -ri 'not published yet' ./jenkins-dock.* | awk '{print $2}' | sort -u
2.401.1
2.401.1-alpine
2.401.1-jdk11
2.401.1-slim
2.401.2-alpine
2.401.3-alpine
2.402-alpine
2.403-alpine
2.404-alpine
2.405-alpine
2.406-alpine
2.407-alpine
2.409-alpine
2.410-alpine
2.411-alpine
2.412-alpine
2.413-alpine
2.414-alpine
2.415-alpine
2.416-alpine
2.417-alpine
2.418-alpine
2.419-alpine
```

=> Closing the issue here and let's follow up in #1690

**Closed by dduportal** 2023-08-21 12:02 UTC
Labels: bug
